"""
This class contains the literal name of the tables in the
LST telescope database
"""


class LstTableNames:
    LST_ANALYSIS_EVALUATION = "LST_ANALYSIS_EVALUATION"
    LST_CONFIGURATION = "LST_CONFIGURATION"
    LST_DATES = "LST_DATES"
    LST_DL1A = "LST_DL1A"
    LST_FILES_OF_SUBRUN = "LST_FILES_OF_SUBRUN"
    LST_PIXEL_GROUP = "LST_PIXEL_GROUP"
    LST_PIXEL_INFORMATION = "LST_PIXEL_INFORMATION"
    LST_PRODUCTIONS = "LST_PRODUCTIONS"
    LST_QP_DATA = "LST_QP_DATA"
    LST_R1_DATA_CHECK_ANALYSIS = "LST_R1_DATA_CHECK_ANALYSIS"
    LST_R1_DATA_CHECK_GENERIC = "LST_R1_DATA_CHECK_GENERIC"
    LST_R1_DATA_CHECK_PLOT = "LST_R1_DATA_CHECK_PLOT"
    LST_R1_DATA_CHECK_SPECIFIC = "LST_R1_DATA_CHECK_SPECIFIC"
    LST_RUN_TYPE = "LST_RUN_TYPE"
    LST_RUNS = "LST_RUNS"
    LST_SUBRUNS = "LST_SUBRUNS"
